### ISSUE TITLE
Propose merging into Terraform

### ISSUE THREAD

**Issue by ojongerius** [russellcardullo/terraform-provider-pingdom#5]
I would consider using it. Terraform folk have been pondering adding one. See discussion/issue https://github.com/hashicorp/terraform/issues/1844

Cheers,

O

**Comment by ksatirli** [comment]
@russellcardullo any thoughts on making this happen? It seems like a useful provider in the same vein as Statuscake and New Relic.

**Comment by chrisferry** [comment]
👍

**Comment by philax** [comment]
Currently, most providers just need to have a provider block and viola! You can begin adding resources...  Is there any plan to make that the case here?  I'd love to try this out with the exact same workflow I have for every other terraform provider.

**Comment by walterheck** [comment]
I'd love to see this too. Note that the [Terraform Community providers](https://www.terraform.io/docs/providers/type/community-index.html) page already has [another pingdom provider](https://bitbucket.org/devops_sysops/pingdom-provider) listed

**Comment by russellcardullo** [comment]
This plugin is now listed on the [Terraform Community providers](https://www.terraform.io/docs/providers/type/community-index.html) page.  From what I gather most plugin development now happens separately instead of being merged into the main terraform binary and support for third party plugins is much easier now.
